name: BookStoreProject CI/CD with AWS CLI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 17 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Maven으로 .war 파일 빌드
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # 4. AWS 자격 증명 설정 (성공이 확인된 단계)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 5. 빌드된 .war 파일을 압축
      - name: Zip the deployment package
        run: |
          WAR_FILE=$(ls target/*.war | head -n 1)
          zip -r deploy.zip $WAR_FILE

      # 6. AWS CLI를 사용하여 직접 배포 (핵심 변경 사항)
      - name: Deploy to Elastic Beanstalk using AWS CLI
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name BookForest \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket="elasticbeanstalk-ap-northeast-2-${{ secrets.AWS_ACCOUNT_ID }}",S3Key="BookForest/${{ github.sha }}.zip" \
            --auto-create-application

          aws s3 cp deploy.zip s3://elasticbeanstalk-ap-northeast-2-${{ secrets.AWS_ACCOUNT_ID }}/BookForest/${{ github.sha }}.zip

          aws elasticbeanstalk update-environment \
            --application-name BookForest \
            --environment-name BookForest-env \
            --version-label ${{ github.sha }}
