name: AWS Credential Test

on:
  push:
    branches:
      - master

jobs:
  test-credentials:
    runs-on: ubuntu-latest

    steps:
      # 1. AWS 자격 증명 설정 (v4 사용 강력 권장)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 2. AWS CLI로 현재 사용자 정보 확인 (가장 중요한 테스트)
      - name: Check current AWS user
        run: |
          aws sts get-caller-identity
